# Generated by Django 4.0.4 on 2022-04-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_alter_slot_doctor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='date',
        ),
    ]
