# Generated by Django 4.0.4 on 2022-04-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_remove_slot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='doctor_id',
            field=models.IntegerField(),
        ),
    ]
