# Generated by Django 4.0.4 on 2022-05-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_appoinment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment',
            name='slot',
        ),
        migrations.AddField(
            model_name='appoinment',
            name='slot',
            field=models.ManyToManyField(to='superadmin.slot'),
        ),
    ]
