# Generated by Django 4.0.4 on 2022-05-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_remove_appoinment_slot_appoinment_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment',
            name='slot',
        ),
        migrations.AddField(
            model_name='appoinment',
            name='slot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='superadmin.slot'),
        ),
    ]
