# Generated by Django 4.0.4 on 2022-05-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_alter_appoinment_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
