# Generated by Django 4.0.4 on 2022-05-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_remove_slot_doctor_name_alter_slot_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='doctor_id',
            field=models.IntegerField(default=None),
        ),
    ]
