# Generated by Django 4.0.4 on 2022-05-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_appoinment_doctor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='doctor_id',
            new_name='doc_id',
        ),
    ]
