# Generated by Django 4.0.4 on 2022-05-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0014_rename_doctor_id_appoinment_doc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment',
            name='doc_id',
        ),
    ]
