# Generated by Django 4.0.4 on 2022-05-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0016_delete_appoinment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(default=None)),
                ('patients_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=30)),
                ('weeks', models.IntegerField()),
                ('timeslot', models.IntegerField()),
                ('description', models.TextField(default=None)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Absent'), (3, 'Canceled')], default=0)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.slot')),
            ],
        ),
    ]
