# Generated by Django 4.0.4 on 2022-05-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0017_appoinment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment',
            name='doc_id',
        ),
    ]
