# Generated by Django 4.0.4 on 2022-05-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0018_remove_appoinment_doc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='superadmin.slot'),
        ),
    ]
